name: Deploy

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

env:
  PACKAGE_OUTPUT: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/Rafal-Kow/index.json'

jobs:
  getVersion:
    if: ${{ github.event.pull_request.merged }}
    name: GetNextVersion
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get next version
      uses: thenativeweb/get-next-version@main
      id: get_next_version
    outputs:
      hasNextVersion: ${{ steps.get_next_version.outputs.hasNextVersion }}
      nextVersion: ${{ steps.get_next_version.outputs.version}}

  buildAndDeploy:
    needs: getVersion
    if: ${{ needs.getVersion.outputs.hasNextVersion }}
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --no-restore --configuration Debug

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Release
        run: dotnet build --no-restore --configuration Release

      - name: Pack Project
        run: dotnet pack --no-restore --no-build --configuration Release -p:PackageVersion=${{ needs.getVersion.outputs.nextVersion }} --output ${{ env.PACKAGE_OUTPUT }}

      - name: Push Package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT }}/*.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.OAUTH_TOKEN }}